In [1]:
import numpy as np 
import pandas as pd
# Pandas Data frames 
# Collections of series, each series is a column in the data frame

# Creating a Data Frame 

# We can create a data frame by using list, arrays , dictionary

In [2]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}


df =pd.DataFrame(data) # so this is how we can create a data frame from a dictionary, the keys will be the column names and the values will be the data in the columns.
print(df) # this will print the data frame in a tabular format, with the column names as the header and the index as the first column.

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
# Creating a Data Frame from a list 
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df1=pd.DataFrame(data_list)
print(df1)       # so in output we can see that the column names are not set,
         # so we can set the column names by passing a list of column names to the columns parameter of the DataFrame constructor.
# we can set this by passing a list of column names to the columns parameter of the DataFrame constructor.
column_names = ['Name', 'Age', 'City', 'Salary']
df1 = pd.DataFrame(data_list, columns=column_names) # so this is how we can set the columns manually 
print("")
print(df1)

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
# Pandas Selection and Indexing of Columns _03
df1

# What if we want to select a single column from the data frame, we can do that by using the column name as an attribute of the data frame.

#df1[0] # this will throw an error as the column name is not set, so we can set the column names by passing a list of column names to the columns parameter of the DataFrame constructor.

df1['Name'] # this will return a series of the Name column, we can also use the dot notation to access the column, but it is not recommended as it can lead to confusion with the methods of the data frame.

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [5]:
# what if we want to select multiple columns from the data frame, we can do that by passing a list of column names to the DataFrame constructor.
# so we have to provide a list of list 
df1[['Name', 'Age']] # this will return a data frame with the selected columns, we can also use the dot notation to access the columns, but it is not recommended as it can lead to confusion with the methods of the data frame.

# So till now we have seen how to select a single column and multiple columns from the data frame, now what if we want to select a single row from the data frame, we can do that by using the iloc method of the data frame.

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [6]:

#--- Creating a new column in the data frame 


df1['Country'] = ['USA', 'France', 'Germany', 'UK'] # so this is how we can create a new column in the data frame, we can also use the insert method of the data frame to insert a new column at a specific position in the data frame.
df1

    Name  Age      City  Salary  Country
0   John   28  New York   65000      USA
1   Anna   34     Paris   70000   France
2  Peter   29    Berlin   62000  Germany
3  Linda   42    London   85000       UK

In [7]:
# So if you wan to remove a columns 
# we want to remove country column from the data frame, we can do that by using the drop method of the data frame.
#df1.drop("Country") # this will give error as we have to specify the axis parameter to drop a column, by default it is set to 0 which means we are dropping a row, so we have to set it to 1 to drop a column.
df1.drop("Country", axis=1) # this will drop the country column from the data frame, we can also use the inplace parameter to drop the column in place, so that we don't have to assign the result to a new variable.

# As we earlier discuss that axis 0 works on the x axis and axis 1 works on the y axis, so when we drop a column we are dropping it from the y axis, so we have to set the axis parameter to 1 to drop a column.
# till here country is not permenant dleted ex in next cell

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:

df1 # here you can see that the country column is still present in the data frame, so if we want to drop the column permanently we have to set the inplace parameter to True, so that the changes are made in place and we don't have to assign the result to a new variable.


#df1.drop(["City"], axis=1, inplace=True)# And when you want to check execute on next cell df1
 # here you can see that the city column is permanently deleted from the data frame, so we don't have to assign the result to a new variable.

    Name  Age      City  Salary  Country
0   John   28  New York   65000      USA
1   Anna   34     Paris   70000   France
2  Peter   29    Berlin   62000  Germany
3  Linda   42    London   85000       UK

In [9]:

df1
#df1.drop(['age','name'], axis=1, inplace=True) for drop the data permenantly multiple colums

    Name  Age      City  Salary  Country
0   John   28  New York   65000      USA
1   Anna   34     Paris   70000   France
2  Peter   29    Berlin   62000  Germany
3  Linda   42    London   85000       UK

In [10]:
df1.drop(0, axis=0) # this will drop the first row from the data frame, we can also use the inplace parameter to drop the row in place, so that we don't have to assign the result to a new variable.

    Name  Age    City  Salary  Country
1   Anna   34   Paris   70000   France
2  Peter   29  Berlin   62000  Germany
3  Linda   42  London   85000       UK

In [11]:

# Pandas Selecting rows !